name: CI Pipeline
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ master ]
    paths-ignore:
      - README.md

jobs:
  check:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          composer install

      - name: Run tests
        run: |
          ./vendor/bin/phpunit tests
